/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_svlabs_svt_matrics_SaarPmcGraph */

#ifndef _Included_com_svlabs_svt_matrics_SaarPmcGraph
#define _Included_com_svlabs_svt_matrics_SaarPmcGraph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_svlabs_svt_matrics_SaarPmcGraph
 * Method:    analysePmcGraphData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_svlabs_svt_matrics_SaarPmcGraph_analysePmcGraphData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
