/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_svlabs_svt_ride_SaarRideFileReader */

#ifndef _Included_com_svlabs_svt_ride_SaarRideFileReader
#define _Included_com_svlabs_svt_ride_SaarRideFileReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_svlabs_svt_ride_SaarRideFileReader
 * Method:    readFile
 * Signature: (Ljava/lang/String;)Lcom/svlabs/svt/ride/RideFile;
 */
JNIEXPORT jobject JNICALL Java_com_svlabs_svt_ride_SaarRideFileReader_readFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
