/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_svlabs_svt_matrics_SaarMatricsGenerator */

#ifndef _Included_com_svlabs_svt_matrics_SaarMatricsGenerator
#define _Included_com_svlabs_svt_matrics_SaarMatricsGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_svlabs_svt_matrics_SaarMatricsGenerator
 * Method:    analyseMatric
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_svlabs_svt_matrics_SaarMatricsGenerator_analyseMatric
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
